# Generated by Django 5.0 on 2023-12-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tin',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trade_licence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
