# Generated by Django 5.0 on 2024-01-03 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='trade_licence',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='tin',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('Founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
