# Generated by Django 5.0 on 2024-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_trade_licence_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trade_licence',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
