# Generated by Django 5.0 on 2024-01-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_trade_licence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='Founder',
            new_name='user',
        ),
    ]
