# Generated by Django 5.0 on 2024-01-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_founder_startup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='licence',
            field=models.FileField(blank=True, null=True, upload_to='licence'),
        ),
    ]
