# Generated by Django 5.0 on 2024-01-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='trade_licence',
        ),
    ]
