# Generated by Django 5.0 on 2023-12-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='job_title',
            new_name='experience_company',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_end',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_start',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='university_end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='university_start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
