# Generated by Django 5.0 on 2023-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_resume_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='university_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
