# Generated by Django 5.0 on 2023-12-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_university_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='university_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='university_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
