# Generated by Django 5.0 on 2023-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_experience_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='university_end_date',
            field=models.DateField(blank=True, max_length=1000, null=True),
        ),
    ]
