# Generated by Django 5.0 on 2023-12-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_title_job_the_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='idel_candidate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirnment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveBigIntegerField(blank=True, default=35000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='the_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
