# Generated by Django 5.0 on 2023-12-18 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_idel_candidate_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 18, 20, 38, 12, 405730, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
