# Generated by Django 5.0 on 2023-12-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_indusrty_job_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approve'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
