# Generated by Django 5.0 on 2023-12-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_admin_comment_job_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='status',
        ),
    ]
