# Generated by Django 5.0 on 2024-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_reportedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
