# Generated by Django 5.0 on 2024-01-05 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
