# Generated by Django 5.0 on 2024-01-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_reportedjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
