# Generated by Django 5.0 on 2024-01-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_applyjob_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indusrty',
            new_name='Industry',
        ),
    ]
